CS349 WatGUI: cs349::StopWatch Class Reference
cs349::StopWatch Class Reference
#include "StopWatch.h"
Public Member Functions
StopWatch (EventQueue *eventQueue, const Rectangle &bounds)
virtual ~StopWatch ()
virtual bool HandleMouseEvent (const MouseEvent &e)
virtual void Paint (Graphics *g)
virtual void HandleTimerEvent (const cs349::TimerEvent &e)
void Start ()
void Reset ()
void Lap ()
void Stop ()
bool IsRunning () const
bool IsReset () const
int NumOfLaps () const
Public Member Functions inherited from cs349::XWindow
XWindow (const string &title, const Rectangle &bounds)
virtual ~XWindow ()
virtual Graphics * GetGraphics ()
virtual void HandlePaintEvent (const PaintEvent &e)
virtual void SetTitle (const char *title)
virtual Rectangle GetBounds () const
virtual void PaintComponent (Graphics *g)
virtual XWindow * GetParentWindow ()
virtual void Repaint (const Rectangle &r)
virtual void SetBounds (const Rectangle &r)
virtual void SetLocation (const Point &p)
virtual void SetParent (Component *parent)
virtual void SetSize (int width, int height)
virtual void SetVisible (bool visible)
long GetWindowNum () const
Public Member Functions inherited from cs349::Component
Component (const string &name)
virtual ~Component ()
virtual string GetName () const
virtual void AddComponent (Component *child)
virtual void RemoveComponent (Component *child)
virtual unsigned long GetBackgroundColor () const
virtual unsigned long GetForegroundColor () const
virtual Component * GetParent ()
virtual bool HandleKeyEvent (const KeyEvent &e)
virtual bool IsPointInComponent (const Point &p) const
virtual bool IsVisible () const
virtual void Repaint ()
virtual void SetBackgroundColor (unsigned long c)
virtual void SetForegroundColor (unsigned long c)
virtual void SetDebugDelay (unsigned long delayMS)
long GetComponentNum () const
vector< Component * > GetDepthFirstInteractorTree () const
vector< Component * > GetBreadthFirstInteractorTree () const
Private Member Functions
string TimeToString (unsigned long count)
Private Member Functions inherited from cs349::TimerListener
TimerListener ()
virtual ~TimerListener ()
Static Private Member Functions
static unsigned long GetCurTime ()
Private Attributes
Timer * timer
unsigned long startTimeMS
unsigned long pausedMS
unsigned long pausedLast
bool running
bool reset
vector< string > laps
Additional Inherited Members
Static Public Member Functions inherited from cs349::XWindow
static XWindow * GetXWindowForWindow (Window window)
static vector< XWindow * > GetWindowList ()
static XWindow * GetXWindow (long windowNum)
Protected Attributes inherited from cs349::Component
vector< Component * > children
All the children of this Component.
Detailed Description
Skeleton of a StopWatch class to complete and augment for A1
Definition at line 17 of file StopWatch.h.
Constructor & Destructor Documentation
cs349::StopWatch::StopWatch (EventQueue * eventQueue, const Rectangle & bounds)
StopWatch derives from XWindow and TimerListener. These classes require the following information passed in.
Parameters
eventQueue The XApplication's event queue
bounds The desired location and size of this StopWatch window.
Definition at line 11 of file StopWatch.cpp.
References pausedLast, pausedMS, reset, running, cs349::Timer::Start(), startTimeMS, and timer.
                                                                        : XWindow(string("Stop Watch!"), bounds) {
     this->running = false;
     this->reset = true;
       pausedMS = 0;
       pausedLast = 0;
     this->timer = new Timer(eventQueue,10,true,this);
     timer->Start();
     startTimeMS = 0;
   }
cs349::StopWatch::~StopWatch () virtual
Definition at line 22 of file StopWatch.cpp.
References cs349::Timer::Stop(), and timer.
{
     timer->Stop();
     delete timer;
     timer = NULL;
   }
Member Function Documentation
unsigned long cs349::StopWatch::GetCurTime () static private
Returns the current time in milliseconds.
Definition at line 28 of file StopWatch.cpp.
Referenced by Lap(), Paint(), Start(), and Stop().
{
     struct timespec tp;
     clock_gettime(CLOCK_REALTIME, &tp);
     return tp.tv_sec * 1000 + tp.tv_nsec / 1000000;
   }
bool cs349::StopWatch::HandleMouseEvent (const MouseEvent & e) virtual
Overrides Component's HandleMouseEvent method.
Reimplemented from cs349::Component.
Definition at line 144 of file StopWatch.cpp.
References cs349::MouseEvent::GetType(), cs349::MouseEvent::GetWhere(), Lap(), cs349::MouseEvent::mouseDrag, cs349::Component::Repaint(), reset, Reset(), running, Start(), Stop(), cs349::Point::x, and cs349::Point::y.
{
       if(e.GetType() == MouseEvent::mouseDrag){
           Component::Repaint();
       }
       else{
     // TODO: Remove the following code and add your own event handling
     // code to handle mouse events
 //    LOG_DEBUG << "Received HandleMouseEvent in StopWatch" << e;
       //get where mouse was clicked
       Point p = e.GetWhere();
       //button click checks
       if(p.y>=190 && p.y<=220){
           if(p.x >=232 && p.x <=282){//start/stop button
               //if stopwatch is running, stop
               if(this->running){
                   Stop();
               }
               else Start();//else start it
               //repaint to ensure when stopped, it is updated right after.
               Component::Repaint();
           }else if(p.x >=292 && p.x <= 342){//reset/lap button
               if(this->running){//lap button
                   Lap();
               }else if(!this->reset){//reset button
                   Reset();
                   //repaint to ensure that it is updated even while timer is paused
                   Component::Repaint();
               }
           }
       }
       }
     return true;
   }
void cs349::StopWatch::HandleTimerEvent (const cs349::TimerEvent & e) virtual
Overrides TimerListener's HandleTimerEvent to be able to routinely update the display.
Implements cs349::TimerListener.
Definition at line 180 of file StopWatch.cpp.
References cs349::Component::Repaint(), and running.
{
     if (this->running) {
       Component::Repaint();
     }
   }
bool cs349::StopWatch::IsReset () const
Query whether the stopwatch was reset or not.
Definition at line 228 of file StopWatch.cpp.
References reset.
Referenced by TEST().
{
         return this->reset;
     }
bool cs349::StopWatch::IsRunning () const
Query whether the stopwatch is running or not.
Definition at line 224 of file StopWatch.cpp.
References running.
Referenced by TEST().
{
     return this->running;
   }
void cs349::StopWatch::Lap ()
Lap functionality on stopwatch
Definition at line 208 of file StopWatch.cpp.
References GetCurTime(), laps, pausedMS, startTimeMS, and TimeToString().
Referenced by HandleMouseEvent().
{
         //to prevent information overflow on the screen, only save the most recent 6 (and show the recent 5)
         if(laps.size()>=6){
             laps.erase(laps.begin());
         }
         unsigned long count = GetCurTime()-startTimeMS-pausedMS; //current exact time of stopwatch
         laps.push_back(TimeToString(count));
     }
int cs349::StopWatch::NumOfLaps () const
Query to see how many laps are saved currently.
Definition at line 232 of file StopWatch.cpp.
References laps.
Referenced by TEST().
{
         return laps.size();
     }
void cs349::StopWatch::Paint (Graphics * g) virtual
Overrides Component's Paint method.
Reimplemented from cs349::Component.
Definition at line 52 of file StopWatch.cpp.
References cs349::Graphics::DrawRect(), cs349::Graphics::DrawText(), cs349::Graphics::FillRect(), GetCurTime(), cs349::XApplication::GetInstance(), laps, pausedMS, reset, running, cs349::Graphics::SetBackgroundColor(), cs349::Graphics::SetForegroundColor(), startTimeMS, and TimeToString().
{
       //set foreground/background colours
       g->SetForegroundColor(XApplication::GetInstance()->GetBlackColor());
       g->SetBackgroundColor(XApplication::GetInstance()->GetBlackColor());
       //blank the screen, TODO: figure out how to do this properly
       g->FillRect(Rectangle(0,0,390,270));
       //reset the foreground color
       g->SetForegroundColor(XApplication::GetInstance()->GetWhiteColor());
       //title + name
       g->DrawText(Point(235,50),string("Visual Stop 1.0"));
       g->DrawText(Point(225,70),string("Edward Yang (CS349)"));
       //Generate the rectangles (buttons) for stop/start/reset/lap
       g->DrawRect(Rectangle(232,190,50,30));
       if(this->running || !this->reset )g->DrawRect(Rectangle(292,190,50,30));
       //Generate the rectangles to visually show time
       g->DrawRect(Rectangle(40,40,40,180));
       g->DrawRect(Rectangle(90,40,40,180));
       g->DrawRect(Rectangle(140,40,40,180));
       std::string time;
       if(reset){//show 0
           time = string("00:00:000");
       }else{
           //initialize
           stringstream ss;
           unsigned long count = GetCurTime()-startTimeMS-pausedMS; //current exact time of stopwatch
           time = TimeToString(count);
           //SHOW LAPS
           //iterate through laps
           int laps_index = 107;//where to show the y
           int offset = 13;//how much to offset each lap on the y axis by
           if(laps.size()>=6){
               g->DrawText(Point(276,laps_index-14),string("..."));
           }
           for(vector<string>::iterator l=laps.begin();l != laps.end();++l){
               if(laps.size()>=6 && l == laps.begin());
               else{
                   g->DrawText(Point(260,laps_index),(*l));
                   laps_index+=offset;//yay...
               }
           }
           //remainder - this feature was added in to ensure the minutes/seconds graphics grow at the proper rate (not just at exact interger units). ie. at 130ms, it should show .130s worth on the seconds graphic, etc.
           double t_minutes_remainder = ((double)count/60000) - (int)count/60000;
           double t_seconds_remainder = ((double)count/1000) - (int)count/1000;
         //for visual representation of time
           //generate the height and starting point of fillrectangle, since Graphics uses top left corner as starting point
           double height;
           //value of minutes/seconds/ms
           int t_minutes = (count/60000)%60;//# of minutes - mod 60 value
           int t_seconds = (count/1000)%60;//# of seconds - mod 60 value
           int t_mseconds = count%1000;//# of ms - mod 1000 value
           //for minutes
           height = (long)t_minutes + t_minutes_remainder;
           height = height*180/10;
           g->FillRect(Rectangle(40,40+180-height,40,height));
           //for seconds
           height = (long)t_seconds + t_seconds_remainder;
           height = height*180/60;
           g->FillRect(Rectangle(90,40+180-height,40,height));
           //for mill seconds
           height = (long)t_mseconds;
           height = height*180/1000;
           g->FillRect(Rectangle(140,40+180-height,40,height));
       }
       //draw the text for time on screen
       g->DrawText(Point(85,247),time);
       //draw the start/stop/reset/pause text
       if(this->running){
           g->DrawText(Point(244,210),string("Stop"));
           g->DrawText(Point(307,210),string("Lap"));//x:300-330
       }else{
           g->DrawText(Point(241,210),string("Start"));//x:400-430,y:170-180
           if(!this->reset) g->DrawText(Point(302,210),string("Reset"));//x:300-330
       }
   }
void cs349::StopWatch::Reset ()
Resets the stopwatch
Definition at line 199 of file StopWatch.cpp.
References laps, pausedLast, pausedMS, and reset.
Referenced by HandleMouseEvent().
{
         //reset the paused times
         pausedMS = 0;
         pausedLast = 0;
         this->reset = true;
         laps.clear();
     }
void cs349::StopWatch::Start ()
Start the stopwatch
Definition at line 187 of file StopWatch.cpp.
References GetCurTime(), pausedLast, pausedMS, reset, running, and startTimeMS.
Referenced by HandleMouseEvent().
{
       this->running = true;
       if(this->reset){//if the watch has been reset, it is a fresh start (not a pause/resume)
           startTimeMS = GetCurTime();
           this->reset = false;
       }else{
           //if not been reset, then it is a pause/resume. hence add to the variable holding data about total paused time
           pausedMS+= GetCurTime()-pausedLast;
       }
   }
void cs349::StopWatch::Stop ()
Stop the stopwatch
Definition at line 218 of file StopWatch.cpp.
References GetCurTime(), pausedLast, and running.
Referenced by HandleMouseEvent().
{
       //update lastpaused, stop -> pause.
       pausedLast = GetCurTime();
     this->running = false;
   }
string cs349::StopWatch::TimeToString (unsigned long count) private
Returns the string value of the given time
Definition at line 34 of file StopWatch.cpp.
Referenced by Lap(), and Paint().
{
         //initialize
         stringstream ss;
         //value of minutes/seconds/ms
         int t_minutes = (count/60000)%60;//# of minutes - mod 60 value
         int t_seconds = (count/1000)%60;//# of seconds - mod 60 value
         int t_mseconds = count%1000;//# of ms - mod 1000 value
         //Generate the Text for time, ensure there are leading 0s
         ss << setfill('0') << setw(2) << t_minutes;
         ss << ":";
         ss << setfill('0') << setw(2) << t_seconds;
         ss << ":";
         ss << setfill('0') << setw(3) << t_mseconds;
         return ss.str();
     }
Member Data Documentation
vector<string> cs349::StopWatch::laps private
Holds the value of laps!
Definition at line 60 of file StopWatch.h.
Referenced by Lap(), NumOfLaps(), Paint(), and Reset().
unsigned long cs349::StopWatch::pausedLast private
The time, in milliseconds, that the stop was last paused In particular, it holds the value the time of the most recent pause.
Definition at line 40 of file StopWatch.h.
Referenced by Reset(), Start(), Stop(), and StopWatch().
unsigned long cs349::StopWatch::pausedMS private
The time, in milliseconds, that the stopwatch has been paused In particular, it keeps a running total of the amount of time needed to subtract from the current time less start time.
Definition at line 34 of file StopWatch.h.
Referenced by Lap(), Paint(), Reset(), Start(), and StopWatch().
bool cs349::StopWatch::reset private
Whether the stopwatch has been reset.
Definition at line 50 of file StopWatch.h.
Referenced by HandleMouseEvent(), IsReset(), Paint(), Reset(), Start(), and StopWatch().
bool cs349::StopWatch::running private
Whether the stopwatch is currently running.
Definition at line 45 of file StopWatch.h.
Referenced by HandleMouseEvent(), HandleTimerEvent(), IsRunning(), Paint(), Start(), Stop(), and StopWatch().
unsigned long cs349::StopWatch::startTimeMS private
The time, in milliseconds, that the stopwatch started
Definition at line 28 of file StopWatch.h.
Referenced by Lap(), Paint(), Start(), and StopWatch().
Timer* cs349::StopWatch::timer private
Timer used to periodically update the stopwatch's display
Definition at line 23 of file StopWatch.h.
Referenced by StopWatch(), and ~StopWatch().
The documentation for this class was generated from the following files:
StopWatch.h
StopWatch.cpp